version: '3.6'
volumes:
  postgres_data:
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: cms-screens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080